---
title: "Data linkage using probabilistic method"
author: "Joshua Edefo"
date: "2024-12-15"
email: "edefojoshua2000@yahoo.com"
output: github_document
---
Step 1: Install and load the necessary packages
Libraries
```{r a, message=FALSE}
library(usethis)
# install.packages("RecordLinkage")
library(RecordLinkage)


```

Other steps

```{r b}

# Step 2: Prepare Your Data

# Example data frames
df1 <- data.frame(
  id = 1:3,
  name = c("John Doe", "Jane Smith", "Alice Johnson"),
  dob = as.Date(c("1980-01-01", "1990-05-15", "1985-07-30")),
  postcode = c("12345", "23456", "34567")
)

df2 <- data.frame(
  id = 4:6,
  name = c("Jon Doe", "Jane Smyth", "Alicia Johnson"),
  dob = as.Date(c("1980-01-01", "1990-05-15", "1985-07-30")),
  postcode = c("12345", "23456", "34567")
)

# Step 3: Create a Record Linkage Object
# Create a RecordLinkage object
linkage <- compare.linkage(df1, df2, 
                           blockfld = c("dob", "postcode"), 
                           strcmp = c("name"))

# Step 4: Perform Probabilistic Linkage

# Calculate weights using the Expectation-Maximization algorithm
linkage <- emWeights(linkage)


#Step 5: Classify Matches
#Classify the matches based on the calculated weights.
matches <- getPairs(linkage)

matches_filtered <- matches[matches$prob >= 0.75 & matches$prob <= 0.85, ]

# View the matched pairs
print(matches_filtered)

```

session information


```{r c}
sessionInfo()

```

